In [4]:
import numpy as np

In [5]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0,20,2)


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand()

0.6758372434543294

In [16]:
np.random.rand(4)

array([0.82582465, 0.92546611, 0.05094659, 0.10539788])

In [17]:
np.random.rand(4,4)

array([[0.61165907, 0.28613022, 0.09710443, 0.75271452],
       [0.21489986, 0.55406999, 0.38821822, 0.85120348],
       [0.37351729, 0.81065775, 0.83481824, 0.3639146 ],
       [0.29096513, 0.15469679, 0.24530223, 0.7405476 ]])

In [18]:
np.random.randint(1,15)

3

In [19]:
np.random.randint(1,100,(10,10))

array([[19,  2, 98, 79, 97, 67, 98, 40, 72, 20],
       [79, 79, 92, 61, 62,  5, 16, 74, 99, 88],
       [61, 79, 29, 24, 75, 66,  5, 99, 44, 54],
       [92, 60, 50, 21, 24, 10, 67,  2, 47, 82],
       [26, 26, 40, 98, 50,  4, 30, 43, 76,  8],
       [66, 44, 24, 11, 93, 16, 64,  5, 92, 17],
       [82, 41, 90,  1, 31, 47, 65, 11, 11, 12],
       [52, 26, 92, 66, 71, 73, 46, 15, 92, 97],
       [89, 66, 34, 89, 30, 87, 77, 93, 92, 56],
       [15, 50, 65, 32, 55, 85, 99, 96,  7, 13]])