In [149]:
import numpy as np

In [150]:
arr = np.random.randint(1,20,10)

In [151]:
matriz = arr.reshape(2,5)
matriz

array([[18, 18, 19, 14,  5],
       [ 1, 15,  8,  2, 19]])

In [152]:
arr

array([18, 18, 19, 14,  5,  1, 15,  8,  2, 19])

In [153]:
arr.max()

19

In [154]:
matriz.max(1)

array([19, 19])

In [155]:
arr.argmax()

2

In [156]:
matriz.argmax(0)

array([0, 0, 0, 0, 1])

In [157]:
arr.min()

1

In [158]:
matriz.min(0)

array([ 1, 15,  8,  2,  5])

In [159]:
arr.argmin()

5

In [160]:
matriz.argmin(1)

array([4, 0])

------------------------------------------

In [161]:
arr

array([18, 18, 19, 14,  5,  1, 15,  8,  2, 19])

In [162]:
arr.ptp()

18

In [163]:
matriz.ptp(0)

array([17,  3, 11, 12, 14])

In [164]:
arr.sort()
arr

array([ 1,  2,  5,  8, 14, 15, 18, 18, 19, 19])

In [165]:
np.percentile(arr,50)

14.5

In [166]:
np.median(arr)

14.5

In [167]:
np.median(matriz,1)

array([ 5., 18.])

In [168]:
np.std(arr)

6.847627326307997

In [169]:
np.var(arr)

46.89

In [170]:
np.mean(arr)

11.9

In [171]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [172]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [173]:
np.concatenate((a,b), axis=1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [ ]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])