In [18]:
import numpy as np

In [19]:
lista = [1,2]
lista

[1, 2]

In [20]:
lista *2

[1, 2, 1, 2]

In [21]:
arr = np.arange(0,10)
arr2 = arr.copy()

Operaciones

In [22]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
1/ arr

/tmp/ipykernel_253/3009366600.py:1: RuntimeWarning: divide by zero encountered in divide
  1/ arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [26]:
arr **2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [27]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [28]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [29]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [30]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [31]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [35]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [36]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [37]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])