In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

In [4]:
arr.shape

(3, 2)

In [5]:
arr

array([[8, 5],
       [4, 5],
       [5, 9]])

In [6]:
arr.reshape(1,6)

array([[8, 5, 4, 5, 5, 9]])

In [ ]:
arr.reshape(2,3)

In [7]:
np.reshape(arr,(1,6))

array([[8, 5, 4, 5, 5, 9]])

In [8]:
arr

array([[8, 5],
       [4, 5],
       [5, 9]])

In [9]:
np.reshape(arr,(2,3),'C')

array([[8, 5, 4],
       [5, 5, 9]])

In [10]:
np.reshape(arr,(2,3),'F')


array([[8, 5, 5],
       [4, 5, 9]])

In [11]:
np.reshape(arr,(2,3),'A')

array([[8, 5, 4],
       [5, 5, 9]])